Vungle/googleads-mobile-android-mediation

- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
this have been created for bug fix:
https://vungle.atlassian.net/browse/AND-2386
> [AND-2386] fix bug from admob PR comments.

- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
This pr have been created for bug fix:
https://vungle.atlassian.net/browse/AND-2398
> [AND-2398] bugfix: MREC refresh failure at version 6.4.11

- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleExtrasBuilder.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
This PR have been created for developing ticket https://vungle.atlassian.net/browse/AND-2437 for AdMob adapter 6.5.x
> [AND-2437]AdMob adapter play MREC audio should be muted by default.

- ThirdPartyAdapters/vungle/vungle/src/main/AndroidManifest.xml
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleListener.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
This PR have been created for the ticket:https://vungle.atlassian.net/browse/AND-2497
> [AND-2497] AdMob adapter onAdEnd event handling

- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
This PR have been created for https://vungle.atlassian.net/browse/AND-2388
> [AND-2388] AdMob improvements

- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
Adapter and plugin information appended multiple times on user-agent for Android SDK. Like VungleDroid/6.4.11;admob/6_4_11;admob/6_4_11;admob/6_4_11;admob/6_4_11;admob/6_4_11;admob/6_4_11;admob/6_4_11;admob/6_4_11;
This PR has been created to fix the issue on adapter side.
> [AND-2516] Append AdMob adapter user-agent to SDK improvement.

- ThirdPartyAdapters/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
Have been created this PR for https://vungle.atlassian.net/browse/AND-2664
The Admob adapter code needs to be able to support banners of varying heights and widths; and make adjustments based on Vungle supported sizes; instead rejecting sizes that are not Vungle compliant.
> [AND-2664] Support smart and adaptive banners in Admob adapters

- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
Discussing whether need to add fixed width on android side similar with iOS.
Solves an issue where we could render Leaderboard into request for 320x100
> [Discuss] Add fixed width for potentials.

- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
This crash only happened in banner leak case.
When the same ad start to load and create banner, at first it will cleanUp previous active banner(maybe leak banner),  in leak banner case, we will receive playback error after we called destroyAd/finishDisplayingAd and in adPlayError callback we called manager#removeActiveAd, the method also called cleanUp and set mVungleBannerAd/mVungleNativeAd to null. So when createBanner#cleanUp come back and run to the next code line will throw NPE caused by the mVungleBannerAd/mVungleNativeAd already set to null value.
> [AND-2724] NPE when create banner and meanwhile remove banner leak.

- ThirdPartyAdapters/vungle/CHANGELOG.md
- ThirdPartyAdapters/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
1. base on 6.5.3 SDK.
2. fix AdMob suggestions.
> Prepare 6.5.3.0 release

- ThirdPartyAdapters/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleListener.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
This PR has been created for making event handling changes base on SDK 6.6.x
> [AND-2497] Event Handling callbacks changes.

- ThirdPartyAdapters/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleListener.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
This PR has been created for propagating all 6.6.x functions to develop.
> Propagate sdk6.6.x to develop

- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
6.5.x-release branch patched AND-2722 improvement changes, we need to merge this patch into 6.6 and 6.7 and so on.
> Merge 6.5.x-release into develop

- ThirdPartyAdapters/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleListener.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
1. sync upstream repo latest source code
2. merge sdk6.6.x functions to develop
> [AND-2801] Propagate sdk6.6.x to develop

- ThirdPartyAdapters/vungle/vungle/build.gradle
> [AND-2592] Test app changes with multiple ad in feed.

- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleExtrasBuilder.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
Prepare to fork 6.7.0 GA RC4 tag.
[AND-2905] Fix start mute for banner/MREC ads. (#58)
[AND-2905]: https://vungle.atlassian.net/browse/AND-2905
> Propagate 67x to develop

- ThirdPartyAdapters/applovin/CHANGELOG.md
- ThirdPartyAdapters/applovin/applovin/build.gradle
- ThirdPartyAdapters/facebook/CHANGELOG.md
- ThirdPartyAdapters/facebook/facebook/build.gradle
- ThirdPartyAdapters/fyber/CHANGELOG.md
- ThirdPartyAdapters/fyber/fyber/build.gradle
- ThirdPartyAdapters/fyber/fyber/src/main/java/com/google/ads/mediation/fyber/FyberMediationAdapter.java
- ThirdPartyAdapters/ironsource/CHANGELOG.md
- ThirdPartyAdapters/ironsource/ironsource/build.gradle
- ThirdPartyAdapters/nend/CHANGELOG.md
- ThirdPartyAdapters/nend/nend/build.gradle
- ThirdPartyAdapters/verizonmedia/CHANGELOG.md
- ThirdPartyAdapters/verizonmedia/verizonmedia/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
Latest commit:
commit 56707c9a0521f06616bf59064e1e7189092976bc (HEAD -> 081320_update_master, upstream/master, origin/081320_update_master)
Author: Mobile Ads Developer Relations <mad-devrel@google.com>
Date:   Tue Aug 11 14:34:35 2020 -0700
#AppLovinAdapter version bump  9.13.2.0
PiperOrigin-RevId: 326103510
> 081320 Update Master from Upstream

- ThirdPartyAdapters/vungle/CHANGELOG.md
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
> Updating Vungle to 6.7.1

- ThirdPartyAdapters/vungle/CHANGELOG.md
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
Updating Vungle to 6.8.1, onAdViewed is no op
> AND-3104 Upgrading to Vungle 6.8.1

- ThirdPartyAdapters/vungle/CHANGELOG.md
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleBannerAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VunglePlayAdCallback.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
https://vungle.atlassian.net/browse/AND-3314
VungleNativeAd is deprecated in 6.10.x version. We will use Banner to replace mrec.
> [AND-3314] Refactor vungle banner adapter. 

- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleNetworkSettings.java
Bug fix for ticket: https://vungle.atlassian.net/browse/AND-3395
> [AND-3395] Fix auto refresh when none Vungle settings

- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
PR for ticket: https://vungle.atlassian.net/browse/AND-3383
> [AND-3383] Inability to mute MREC after transitioning from VungleNativeAd to VungleBanner

- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleBannerAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
PR for ticket https://vungle.atlassian.net/browse/AND-3227
- Based on 6.10.x-release branch which already merged the latest upstream/master branch, that means based on AdMob Sdk V20.0.0
> [AND-3227] AdError enhancement.

- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
Checking static configuration before init is called
> [AND-3786] COPPA Sending Status on Init

- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleExtrasBuilder.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleNativeAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleNativeAdapter.java
Native adapter for AdMob. Currently blocked on AdMob dashboard for native ad environment.
Test app PR: https://github.com/Vungle/admob-adapter-testapp-android/pull/59
spec: https://developers.google.com/admob/android/native/native-custom-events?hl=en#samplecustomevent_excerpt
> [AND-3637] AdMob Native ads adapter

- ThirdPartyAdapters/vungle/CHANGELOG.md
- ThirdPartyAdapters/vungle/vungle/build.gradle
1. merged upstream/master branch into 6.11.x-release branch.
2. based on 6.11.x-release branch.
> [AND-3972] AdMob 6.11.0-ea2-RC1 release

- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbInterstitialAd.java
Bugfix for ticket: https://vungle.atlassian.net/browse/AND-3975
> [AND-3975] Bugfix: can not load NON-HB rewarded ads.

- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
PR for ticket: https://vungle.atlassian.net/browse/AND-4021
> [AND-4021] release 6.11.0 GA-RC2 build

- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleConsent.java
PR for ticket: https://vungle.atlassian.net/browse/AND-4088
> [AND-4088] Bugfix: gdpr no effect for the config request.

- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleNativeAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleNativeAdapter.java
PR for ticket: https://vungle.atlassian.net/browse/AND-4060
> [AND-4060] Native Bidding support

- ThirdPartyAdapters/vungle/CHANGELOG.md
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
1. Prepare for 6.12.1.0 adapter build
2. Adding Banner/MREC bidding
> [AND-4318] Adding Banner/MREC bidding support

- ThirdPartyAdapters/vungle/CHANGELOG.md
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleConsent.java
pr for ticket: https://vungle.atlassian.net/browse/AND-4342
> [AND-4342] New wrapper API for CCPA

- ThirdPartyAdapters/vungle/CHANGELOG.md
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleConsent.java
Prepare for 6.12.1.0 adapter build
Adding Banner/MREC bidding
> [AND-4315] Release 6.12.1.0

- ThirdPartyAdapters/vungle/settings.gradle
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbInterstitialAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbNativeAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbRewardedAd.java
[AND-4463] This commit adds setting the extra object with the watermark to send to the Vungle SDK
[AND-4463]: https://vungle.atlassian.net/browse/AND-4463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AND-4463] This commit adds setting the extra object with the watermark to send to the Vungle SDK

- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleAdapter.java
pr for ticket: https://vungle.atlassian.net/browse/AND-4577
> [AND-4577] Upgrade AdMob SDK to 22.0.0

- ThirdPartyAdapters/vungle/CHANGELOG.md
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbInterstitialAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbNativeAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbRewardedAd.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleConsent.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
pr for ticket: https://vungle.atlassian.net/browse/AND-4573
> [AND-4573] Remove vng COPPA settings from adapter.

- ThirdPartyAdapters/liftoffmonetize/build.gradle
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/build.gradle
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/main/java/com/google/ads/mediation/vungle/VungleFactory.kt
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAd.java
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/VungleBannerSizeAdapterTest.kt
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/VungleMediationAdapterTest.kt
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAdTest.kt
pr for ticket: https://vungle.atlassian.net/browse/AND-4959
> [AND-4959] adapter changes to support in-feed videos

- ThirdPartyAdapters/liftoffmonetize/CHANGELOG.md
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/build.gradle
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/main/java/com/google/ads/mediation/vungle/renderers/VungleAppOpenAd.kt
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAd.java
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbInterstitialAd.java
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbNativeAd.java
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbRewardedAd.java
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/VungleBannerSizeAdapterTest.kt
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/VungleInitializerTest.kt
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/VungleMediationAdapterTest.kt
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/VungleRewardedAdTest.kt
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/rtb/VungleRtbAppOpenAdTest.kt
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAdTest.kt
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/rtb/VungleRtbInterstitialAdTest.kt
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/rtb/VungleRtbNativeAdTest.kt
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/rtb/VungleRtbRewardedAdTest.kt
- ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/waterfall/VungleWaterfallAppOpenAdTest.kt
https://vungle.atlassian.net/browse/AND-5068
> [AND-5068] Admob adapter for config less SDK init
